<?php

namespace App\Http\Requests\Product;

use App\Http\Requests\traits\APIRequest;
use App\Models\Category;
use App\Models\Package;
use App\Models\SocialMediaLink;
use App\Models\Subcategory;
use Illuminate\Foundation\Http\FormRequest;

class ProductEditRequest extends FormRequest
{
    use APIRequest;
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [
            'name'  =>  'string|max:30',
            'description'   =>  'string|min:250',
            'summary'   =>  'string|max:350',
            'price'     =>  'numeric',
            'img'       =>  'string|max:30',
            'category'  =>  'integer|exists:'.(new Category())->getTable().',id',
            'lifetime'  =>  'boolean',
            'until'     =>  'date_format:d/m/Y',
            'assets'    =>  'json',
            'subcategory'=> 'integer|exists:'.(new Subcategory())->getTable().',id',
            'data'      =>  'json',
            'packages'  =>  'json',
            'packages.*'  =>  'integer|exists:'.(new Package())->getTable().',id',
            'social_media'  =>  'json',
            'social_media.*'  =>  'json',
            'social_media.*.id'    =>  'integer|exists:'.(new SocialMediaLink())->getTable().',id',
            'social_media.*.link'         =>  'url'
        ];

        if ($this->route()->getName()==='add')
        {
            foreach ($rules as $key => $rule)
            {
                $rules[$key] = 'required|'.$rule;
            }
        }

        return $rules;
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
